baseurl = "https://anthonybarente.com"
title = "ANTHONY BARENTE"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Anthony Barente"
  info = "Data Scientist and Computational Biologist"
  description = "Anthony Barente's personal website"
  keywords = "data science,computational biology,mass spectromety,drug development"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/anthonyofseattle/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/anthonybarente/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

# Other
[caches]
  [caches.images]
    dir = ':cacheDir/images'
