baseurl = "https://anthonybarente.com"
title = "Anthony Barente's Personal Site"
theme = "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"

# Other
[caches]
  [caches.images]
    dir = ':cacheDir/images'
